### ISSUE TITLE
Commands::Deploy Error: Xcodeproj::Informative

### ISSUE THREAD

**Issue by kiyoshi-tokunaga** [DeployGate/deploygate-cli#100]
# Status

deploygate-cli ver 0.2.1
# Error message

 `project.pbxproj` doesn't exist.

# Backtrace

```
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:64:in `read'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:13:in `read_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:193:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/analyze.rb:99:in `target_project_setting'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/analyze.rb:87:in `target_build_configration'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/analyze.rb:80:in `target_xcode_setting_provisioning_profile_uuid'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:34:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/usr/bin/dg:23:in `load'
/usr/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you, feedback!
Please try since has released a new ver!
https://rubygems.org/gems/deploygate/versions/0.2.2

**Comment by henteko** [comment]
This issue will get closed because old.
