### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by yuki122** [DeployGate/deploygate-cli#104]
# Status
deploygate-cli ver 0.2.1

# Error message
Could not find latest API Key from the Dev Portal - the server might be slow right now

# Backtrace
```
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:30:in `api_key'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:38:in `send_login_request'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:219:in `do_login'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:182:in `login'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:60:in `login'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:22:in `login'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:77:in `login'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_center.rb:11:in `initialize'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/2.3.0/singleton.rb:142:in `new'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/2.3.0/singleton.rb:140:in `instance'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_centers/device.rb:27:in `register!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/add_devices.rb:30:in `block in run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/add_devices.rb:29:in `each'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/add_devices.rb:29:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:86:in `block (2 levels) in run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/Users/yuki/.rbenv/versions/2.3.1/bin/dg:23:in `load'
/Users/yuki/.rbenv/versions/2.3.1/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you, feedback!
This issue is closed because it is the same as #96 .
