### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by galapagosit** [DeployGate/deploygate-cli#107]
# Status

deploygate-cli ver 0.2.2
# Error message

execution expired
# Backtrace

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:367:in `<<'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:567:in `dump_file'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:488:in `block in dump'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `each'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `dump'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:924:in `dump'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:612:in `block in query'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:610:in `query'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:161:in `query'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient.rb:1106:in `do_get_stream'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient.rb:899:in `block (2 levels) in do_request_async'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient.rb:966:in `protect_keep_alive_disconnected'
/Library/Ruby/Gems/2.0.0/gems/httpclient-2.2.7/lib/httpclient.rb:898:in `block in do_request_async'
```

**Comment by henteko** [comment]
This issue will get closed because old.
