### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by kgyk1993** [DeployGate/deploygate-cli#108]
# Status

deploygate-cli ver 0.2.2
# Error message

<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>
# Backtrace

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:434:in `parse_response'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/portal/portal_client.rb:261:in `create_device!'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/portal/device.rb:155:in `create!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/xcode/member_centers/device.rb:30:in `register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/commands/add_devices.rb:30:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/commands/add_devices.rb:29:in `each'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/commands/add_devices.rb:29:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/command_builder.rb:86:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/lib/deploygate/command_builder.rb:123:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.2/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
