### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by Ryohu** [DeployGate/deploygate-cli#110]
# Status

deploygate-cli ver 0.2.2
# Error message

execution expired
# Backtrace

```
/Users/hashimotoryo/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
/Users/hashimotoryo/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
/Users/hashimotoryo/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/session.rb:367:in `<<'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/http.rb:567:in `dump_file'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/http.rb:488:in `block in dump'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `each'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `dump'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/http.rb:924:in `dump'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/session.rb:612:in `block in query'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/session.rb:610:in `query'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient/session.rb:161:in `query'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient.rb:1106:in `do_get_stream'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient.rb:899:in `block (2 levels) in do_request_async'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient.rb:966:in `protect_keep_alive_disconnected'
/Users/hashimotoryo/.rvm/gems/ruby-2.1.2/gems/httpclient-2.2.7/lib/httpclient.rb:898:in `block in do_request_async'
```

**Comment by henteko** [comment]
This issue will get closed because old.
