### ISSUE TITLE
Commands::Deploy Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by FutoshiYamamoto** [DeployGate/deploygate-cli#111]
# Status

deploygate-cli ver 0.2.2
# Error message

{"responseId"=>"fbc319ff-67ca-4579-8419-faea6d67c46d", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"An invalid value &#x27;jp company game &#x24;&#x7b;PRODUCT_NAME&#x7d;&#x27; was provided for the parameter &#x27;appIdName&#x27;.", "creationTimestamp"=>"2016-06-30T14:33:45Z", "protocolVersion"=>"QH65B2", "requestId"=>"", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com:443/services-account/QH65B2/account/ios/identifiers/addAppId.action", "httpCode"=>200, "suppressed"=>[], "validationMessages"=>[{"validationKey"=>"appIdName", "validationUserMessage"=>"An invalid value &#x27;jp company game &#x24;&#x7b;PRODUCT_NAME&#x7d;&#x27; was provided for the parameter &#x27;appIdName&#x27;."}]}
# Backtrace

```
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:434:in `parse_response'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.27.2/lib/spaceship/portal/portal_client.rb:178:in `create_app!'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.27.2/lib/spaceship/portal/app.rb:97:in `create!'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/xcode/member_centers/app.rb:25:in `create!'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/xcode/export.rb:207:in `create_provisioning'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/lib/deploygate/command_builder.rb:123:in `run'
/Users/FYamamoto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.2.2/bin/dg:6:in `<top (required)>'
/Users/FYamamoto/.rbenv/versions/2.3.1/bin/dg:22:in `load'
/Users/FYamamoto/.rbenv/versions/2.3.1/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
