### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by masat4926** [DeployGate/deploygate-cli#118]
# Status

deploygate-cli ver 0.2.3
# Error message

Error parsing xcode file using `xcodebuild -list -workspace /Users/CapsClinicSystem/Desktop/git/ClinicSystem_MEI_Web/mnys_mei_webview.xcodeproj/project.xcworkspace`
# Backtrace

```
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/project.rb:293:in `raw_info'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/project.rb:317:in `parsed_info'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/project.rb:102:in `schemes'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/xcode/analyze.rb:22:in `initialize'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/commands/deploy/build.rb:31:in `new'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/commands/deploy/build.rb:31:in `ios'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/lib/deploygate/command_builder.rb:123:in `run'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.2.3/bin/dg:6:in `<top (required)>'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/bin/dg:23:in `load'
/Users/CapsClinicSystem/.rbenv/versions/2.2.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
launchy
