### ISSUE TITLE
Commands::Deploy Error: NoMethodError

### ISSUE THREAD

**Issue by a0027988** [DeployGate/deploygate-cli#120]
# Status

deploygate-cli ver 0.3.0
# Error message

undefined method `build_configuration_list' for nil:NilClass
# Backtrace

```
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/xcode/analyze.rb:87:in `target_build_configration'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/xcode/analyze.rb:80:in `target_xcode_setting_provisioning_profile_uuid'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/commands/deploy/build.rb:34:in `ios'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/commands/deploy/build.rb:17:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/commands/deploy.rb:16:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/lib/deploygate/command_builder.rb:125:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.3.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
