### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by a0027988** [DeployGate/deploygate-cli#121]
# Status

deploygate-cli ver 0.3.0
# Error message

execution expired
# Backtrace

```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:367:in `<<'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:567:in `dump_file'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:488:in `block in dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:485:in `dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/http.rb:924:in `dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:612:in `block in query'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:120:in `timeout'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:610:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:161:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:1106:in `do_get_stream'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:899:in `block (2 levels) in do_request_async'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:966:in `protect_keep_alive_disconnected'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:898:in `block in do_request_async'
```

**Comment by henteko** [comment]
This issue will get closed because old.
