### ISSUE TITLE
Commands::Deploy Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by opst-oonishi** [DeployGate/deploygate-cli#123]
# Status

deploygate-cli ver 0.3.1
# Error message

Couldn't download certificate, got this instead: {"responseId"=>"61233719-c898-44ff-8354-b9087f62300b", "resultCode"=>1200, "resultString"=>"webservice.certificate.downloadNotAllowed", "userString"=>"You are not permitted to download this certificate.", "creationTimestamp"=>"2016-09-09T07:39:31Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200}
# Backtrace

```
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.32.1/lib/spaceship/portal/portal_client.rb:300:in `download_certificate'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.32.1/lib/spaceship/portal/certificate.rb:309:in `download_raw'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:49:in `block in all_create'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `each'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `all_create'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/export.rb:216:in `create_provisioning'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/lib/deploygate/command_builder.rb:125:in `run'
/Users/oonishi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.3.1/bin/dg:6:in `<top (required)>'
/Users/oonishi/.rbenv/versions/2.2.3/bin/dg:23:in `load'
/Users/oonishi/.rbenv/versions/2.2.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
