### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by danielbair** [DeployGate/deploygate-cli#134]
# Status

deploygate-cli ver 0.4.0
# Error message

execution expired
# Backtrace

```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:92:in `<<'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:582:in `dump_file'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:500:in `block in dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:497:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:497:in `dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:962:in `dump'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:510:in `block in query'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:508:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:174:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1278:in `do_get_stream'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1048:in `block (2 levels) in do_request_async'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1047:in `block in do_request_async'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
