### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by Sonbg** [DeployGate/deploygate-cli#135]
# Status

deploygate-cli ver 0.4.0
# Error message

Error building the application - see the log above
# Backtrace

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/gym-1.9.0/lib/gym/error_handler.rb:53:in `handle_build_error'
/Library/Ruby/Gems/2.0.0/gems/gym-1.9.0/lib/gym/runner.rb:101:in `block in build_app'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `call'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `execute'
/Library/Ruby/Gems/2.0.0/gems/gym-1.9.0/lib/gym/runner.rb:97:in `build_app'
/Library/Ruby/Gems/2.0.0/gems/gym-1.9.0/lib/gym/runner.rb:12:in `run'
/Library/Ruby/Gems/2.0.0/gems/gym-1.9.0/lib/gym/manager.rb:10:in `work'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/xcode/ios.rb:30:in `build'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/commands/deploy/build.rb:46:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/lib/deploygate/command_builder.rb:125:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.0/bin/dg:6:in `<top (required)>'
/usr/bin/dg:23:in `load'
/usr/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
