### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by yuki122** [DeployGate/deploygate-cli#136]
# Status

deploygate-cli ver 0.4.0
# Error message

<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>
# Backtrace

```
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:447:in `parse_response'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.32.4/lib/spaceship/portal/portal_client.rb:256:in `create_device!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.32.4/lib/spaceship/portal/device.rb:155:in `create!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/xcode/member_centers/device.rb:30:in `register!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/commands/add_devices.rb:61:in `each'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/commands/add_devices.rb:61:in `register!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/commands/add_devices.rb:43:in `device_register'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/commands/add_devices.rb:29:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/lib/deploygate/command_builder.rb:125:in `run'
/Users/yuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.4.0/bin/dg:6:in `<top (required)>'
/Users/yuki/.rbenv/versions/2.3.1/bin/dg:23:in `load'
/Users/yuki/.rbenv/versions/2.3.1/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
