### ISSUE TITLE
Commands::Deploy Error: Xcodeproj::Informative

### ISSUE THREAD

**Issue by atsushiootani** [DeployGate/deploygate-cli#141]
# Status
deploygate-cli ver 0.4.1

# Error message
[31m[!] The plist file at path `/Users/otaniatsushi1/PROGRAM/ruri/balls/balls/proj.ios_mac/project.pbxproj` doesn't exist.
[0m

# Backtrace
```
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:64:in `read'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:13:in `read_plist'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:193:in `initialize_from_file'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:153:in `target_project'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:149:in `target_project_setting'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:137:in `target_build_configration'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:83:in `target_xcode_setting_provisioning_profile_uuid'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:35:in `ios'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.55.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:125:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/bin/dg:6:in `<top (required)>'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/bin/dg:23:in `load'
/Users/otaniatsushi1/.rbenv/versions/2.2.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
