### ISSUE TITLE
Commands::Deploy Error: TypeError

### ISSUE THREAD

**Issue by shmhlove** [DeployGate/deploygate-cli#148]
# Status
deploygate-cli ver 0.4.1

# Error message
no implicit conversion of nil into String

# Backtrace
```
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:21:in `dirname'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/xcode/analyze.rb:21:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:31:in `new'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:31:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:125:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by dzwicker** [comment]
update the gem system `gem update --system`

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
