### ISSUE TITLE
Commands::AddDevices Error: Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by dezamisystem** [DeployGate/deploygate-cli#153]
# Status
deploygate-cli ver 0.4.1

# Error message
Connection reset by peer - SSL_connect

# Backtrace
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:424:in `block in send_request'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:341:in `with_retry'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:423:in `send_request'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:398:in `request'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/portal/portal_client.rb:29:in `teams'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/portal/portal_client.rb:55:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.4/lib/spaceship/launcher.rb:62:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/xcode/member_center.rb:12:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `block in instance'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `instance'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/xcode/member_centers/device.rb:27:in `register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:61:in `register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:43:in `device_register'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:29:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:125:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.4.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
