### ISSUE TITLE
dg deploy command makes duplicate -configuration args for gym/xcodebuild.

### ISSUE THREAD

**Issue by ecoopnet** [DeployGate/deploygate-cli#154]
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

# log
```
14:32:04]: $ xcodebuild -list -workspace /Users/hoge/path/to/proj/MyProj.xcworkspace -configuration Release
[14:32:05]: $ xcodebuild clean -showBuildSettings -workspace /Users/hoge/path/to/proj/MyProj.xcworkspace -scheme MyPRoj -configuration Release

+----------------------+---------------------------------------------------------------------------+
|                                      Summary for gym 1.9.0                                       |
+----------------------+---------------------------------------------------------------------------+
| export_method        | ad-hoc                                                                    |
| workspace            | /Users/hoge/path/to/proj/MyProj... |
| configuration        | Release                                                                   |
| scheme               | MyProj                                                                 |
| destination          | generic/platform=iOS                                                      |
| output_name          | MyProj                                                                 |
| clean                | false                                                                     |
| output_directory     | .                                                                         |
| silent               | false                                                                     |
| use_legacy_build_api | false                                                                     |
| buildlog_path        | ~/Library/Logs/gym                                                        |
+----------------------+---------------------------------------------------------------------------+

[14:32:05]: $ set -o pipefail && xcodebuild -workspace /Users/hoge/path/to/proj/MyProj.xcworkspace -scheme MyProj -configuration Release -configuration 'Release' -destination 'generic/platform=iOS' -archivePath /Users/hoge/Library/Developer/Xcode/Archives/2016-12-17/MyProj\ 2016-12-17\ 14.32.05.xcarchive archive | tee /Users/hoge/Library/Logs/gym/MyProj-MyProj.log | xcpretty
[14:32:06]: ▸ xcodebuild: error: option '-configuration' may only be provided once
```
# Status
deploygate-cli ver 0.4.1

# Error message
Error building the application - see the log above

# Backtrace
```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.60.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.60.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/error_handler.rb:53:in `handle_build_error'
/usr/local/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:101:in `block in build_app'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:88:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:97:in `build_app'
/usr/local/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:12:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/manager.rb:10:in `work'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/xcode/ios.rb:30:in `build'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:50:in `ios'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/commands/deploy.rb:16:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.60.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:125:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.4.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
