### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by tomonari-t** [DeployGate/deploygate-cli#157]
# Status
deploygate-cli ver 0.5.0

# Error message
Error packaging up the application

# Backtrace
```
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/gym/lib/gym/error_handler.rb:87:in `handle_package_error'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/gym/lib/gym/runner.rb:128:in `block in package_app'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/gym/lib/gym/runner.rb:124:in `package_app'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/gym/lib/gym/runner.rb:19:in `run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/gym/lib/gym/manager.rb:14:in `work'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/xcode/ios.rb:30:in `build'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/commands/deploy/build.rb:50:in `ios'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.1.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/lib/deploygate/command_builder.rb:125:in `run'
/Users/apple/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/deploygate-0.5.0/bin/dg:6:in `<top (required)>'
/Users/apple/.rbenv/versions/2.4.0/bin/dg:22:in `load'
/Users/apple/.rbenv/versions/2.4.0/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.1

**Comment by tomonari-t** [comment]
Thank you so much , I succeeded.
Sorry for replying too late...
Thanks!
