### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by hyrofumi** [DeployGate/deploygate-cli#161]
# Status
deploygate-cli ver 0.5.1

# Error message
Error parsing xcode file using `xcodebuild -list -workspace /Users/[user name]/[path ro project]/[project name].xcodeproj/project.xcworkspace`

# Backtrace
```
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/project.rb:373:in `raw_info'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/project.rb:439:in `parsed_info'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/project.rb:102:in `schemes'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/xcode/analyze.rb:25:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/commands/deploy/build.rb:31:in `new'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/commands/deploy/build.rb:31:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/lib/deploygate/command_builder.rb:125:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Sorry for the late response.

Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.3
