### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by shinichy** [DeployGate/deploygate-cli#163]
# Status
deploygate-cli ver 0.5.2

# Error message
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>

# Backtrace
```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/client.rb:449:in `parse_response'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/portal/portal_client.rb:282:in `create_device!'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/portal/device.rb:161:in `create!'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/xcode/member_centers/device.rb:30:in `register!'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/commands/add_devices.rb:61:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/commands/add_devices.rb:61:in `register!'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/commands/add_devices.rb:43:in `device_register'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/commands/add_devices.rb:29:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/lib/deploygate/command_builder.rb:125:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/deploygate-0.5.2/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.3
