### ISSUE TITLE
 No applicable devices found.

### ISSUE THREAD

**Issue by kazuph** [DeployGate/deploygate-cli#17]
- OSX 10.11.1 El Captitan
- Xcode 7.1
- deploygate-cli 0.0.3

# Error message

```
2015-10-31 23:03:45.919 xcodebuild[15854:5313915] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fcf4d2406b0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
```
Error packaging up the application

# Backtrace (auto created)
```
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/error_handler.rb:86:in `handle_package_error'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:102:in `block in package_app'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.1/lib/fastlane_core/command_executor.rb:62:in `call'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.1/lib/fastlane_core/command_executor.rb:62:in `execute'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:98:in `package_app'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:16:in `run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/manager.rb:8:in `work'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/builds/ios.rb:27:in `build'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/commands/deploy/build.rb:55:in `ios'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/command_builder.rb:36:in `block (2 levels) in run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/command_builder.rb:58:in `run'
/Users/kazuph/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/bin/dg:6:in `<top (required)>'
/Users/kazuph/.rbenv/versions/2.2.2/bin/dg:23:in `load'
/Users/kazuph/.rbenv/versions/2.2.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@kazuph 
Thanks for the feedback.

Is this project can be archived and export in Xcode?

**Comment by oppai** [comment]
I have this problem too.

- OSX 10.10.5
- xcode 7.1
- deploygate-cli ver 0.0.6

#### Error message
```log
[01:52:46]: Successfully stored the archive. You can find it in the Xcode Organizer.                                                                           [18/1819]
[01:52:46]: $ /usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1449766366.plist' -archivePath '/Users/kodam/Library/Developer/Xcode/Archive
s/2015-12-11/MangaReco 2015-12-11 01.51.49.xcarchive' -exportPath '/tmp/1449766366'
2015-12-11 01:52:46.550 xcodebuild[9608:2456255] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Lib
rary/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 01:52:46.552 xcodebuild[9608:2456255] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Lib
rary/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 01:52:46.554 xcodebuild[9608:2456255] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Lib
rary/Application Support/Developer/Shared/Xcode/Plug-ins/ClangFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 01:52:46.555 xcodebuild[9608:2456255] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Lib
rary/Application Support/Developer/Shared/Xcode/Plug-ins/Backlight.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 01:52:46.557 xcodebuild[9608:2456255] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Lib
rary/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 01:52:46.773 xcodebuild[9608:2456255] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/9q/8s
s_h6bs4jn_p5x5pn64nldm0000gn/T/MangaReco_2015-12-11_01-52-46.772.xcdistributionlogs'.
2015-12-11 01:52:47.622 xcodebuild[9608:2456255] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fc42dbe4370>: Error Domain=IDEDistributionErrorDoma
in Code=14 "No applicable devices found." UserInfo=0x7fc42dee8270 {NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo=0x7fc42dee8270 {NSLocalizedDescription=No applicable devices found.}

** EXPORT FAILED **
[01:52:47]: Exit status: 70
Current Xcode used to build: /Applications/Xcode.app/Contents/Developer
 (via xcode-select)
```

Exporting IPA by dg was failed. But exporting IPA manually was successed.

```
[~/Documents/manga/MangaReco|kodam]$/usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1449766132.plist' -archivePath '/Users/kodam/Library/Developer/Xcode/Archives/2015-12-11/MangaReco 2015-12-11 01.47.50.xcarchive' -exportPath '/tmp/1449766132'
2015-12-11 02:04:52.721 xcodebuild[10071:2461261] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 02:04:52.723 xcodebuild[10071:2461261] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 02:04:52.724 xcodebuild[10071:2461261] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ClangFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 02:04:52.725 xcodebuild[10071:2461261] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Backlight.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 02:04:52.726 xcodebuild[10071:2461261] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-12-11 02:04:52.946 xcodebuild[10071:2461261] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/9q/8ss_h6bs4jn_p5x5pn64nldm0000gn/T/MangaReco_2015-12-11_02-04-52.946.xcdistributionlogs'.
Exported MangaReco 2015-12-11 01.47.50.xcarchive to: /tmp/1449766132
** EXPORT SUCCEEDED **

```
