### ISSUE TITLE
Commands::AddDevices Error: Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by katahana0223** [DeployGate/deploygate-cli#172]
# Status
deploygate-cli ver 0.5.4

# Error message
Connection reset by peer - SSL_connect

# Backtrace
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:33:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/connection.rb:386:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.0.1/lib/faraday/connection.rb:186:in `post'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/client.rb:534:in `block in send_request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/client.rb:386:in `with_retry'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/client.rb:533:in `send_request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/client.rb:430:in `request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/portal/portal_client.rb:29:in `teams'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/launcher.rb:62:in `select_team'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/xcode/member_center.rb:12:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `block in instance'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `instance'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/xcode/member_centers/device.rb:27:in `register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:61:in `register!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:51:in `device_register'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:29:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:125:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.5.4/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by toruuetani** [comment]
+1

**Comment by henteko** [comment]
Thank you for your feedback!
I just released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.5

**Comment by toruuetani** [comment]
Thank you for your update.
This error is resolved.

**Comment by henteko** [comment]
@toruuetani Thanks!
