### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by posaunehm** [DeployGate/deploygate-cli#173]
# Status
deploygate-cli ver 0.5.4

# Error message
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>

# Backtrace
```
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/client.rb:453:in `parse_response'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/portal/portal_client.rb:375:in `create_device!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/spaceship/lib/spaceship/portal/device.rb:155:in `create!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/xcode/member_centers/device.rb:30:in `register!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:61:in `each'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:61:in `register!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:43:in `device_register'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/add_devices.rb:29:in `run'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:125:in `run'
/Users/posaunehm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/bin/dg:6:in `<top (required)>'
/Users/posaunehm/.rbenv/versions/2.2.3/bin/dg:23:in `load'
/Users/posaunehm/.rbenv/versions/2.2.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you for your feedback!
I just released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.5
