### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by lulurun** [DeployGate/deploygate-cli#177]
# Status
deploygate-cli ver 0.5.4

# Error message
Error packaging up the application

# Backtrace
```
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/gym/lib/gym/error_handler.rb:87:in `handle_package_error'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/gym/lib/gym/runner.rb:128:in `block in package_app'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/gym/lib/gym/runner.rb:124:in `package_app'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/gym/lib/gym/runner.rb:19:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/gym/lib/gym/manager.rb:14:in `work'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/xcode/ios.rb:30:in `build'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/deploy/build.rb:55:in `ios'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/deploy/build.rb:22:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/commands/deploy.rb:16:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/lib/deploygate/command_builder.rb:125:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.5.4/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you for your feedback!
I just released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.6
