### ISSUE TITLE
Commands::Deploy Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by aarifsumra** [DeployGate/deploygate-cli#178]
# Status
deploygate-cli ver 0.5.5

# Error message
Couldn't download certificate, got this instead: 

# Backtrace
```
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/fastlane-2.26.1/spaceship/lib/spaceship/portal/portal_client.rb:434:in `download_certificate'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/fastlane-2.26.1/spaceship/lib/spaceship/portal/certificate.rb:310:in `download_raw'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/member_centers/provisioning_profile.rb:49:in `block in all_create'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `each'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `all_create'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/export.rb:219:in `create_provisioning'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/commands/deploy/build.rb:43:in `ios'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/lib/deploygate/command_builder.rb:125:in `run'
/Users/aarif/.rvm/gems/ruby-2.3.3/gems/deploygate-0.5.5/bin/dg:6:in `<top (required)>'
/Users/aarif/.rvm/gems/ruby-2.3.3/bin/dg:22:in `load'
/Users/aarif/.rvm/gems/ruby-2.3.3/bin/dg:22:in `<main>'
/Users/aarif/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/aarif/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by henteko** [comment]
Thank you for your feedback!
I just released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.6
