### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by SatoTakeshiX** [DeployGate/deploygate-cli#180]
# Status
deploygate-cli ver 0.5.5

# Error message
xcodebuild -list timed-out after 30 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT

# Backtrace
```
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/project.rb:382:in `rescue in raw_info'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/project.rb:377:in `raw_info'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/project.rb:452:in `parsed_info'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/project.rb:102:in `schemes'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/xcode/analyze.rb:25:in `initialize'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/commands/deploy/build.rb:36:in `new'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fastlane-2.27.0.beta.20170412010036/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/lib/deploygate/command_builder.rb:125:in `run'
/Users/satoutakeshi/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/deploygate-0.5.5/bin/dg:6:in `<top (required)>'
/Users/satoutakeshi/.rbenv/versions/2.1.8/bin/dg:23:in `load'
/Users/satoutakeshi/.rbenv/versions/2.1.8/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you for your feedback!
I just released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.6
