### ISSUE TITLE
Commands::Deploy Error: Faraday::SSLError

### ISSUE THREAD

**Issue by YouShinStransa** [DeployGate/deploygate-cli#187]
# Status
deploygate-cli ver 0.6.0

# Error message
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

# Backtrace
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `post'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/client.rb:672:in `block in send_request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/client.rb:516:in `with_retry'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/client.rb:671:in `send_request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/client.rb:560:in `request'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/portal/portal_client.rb:474:in `provisioning_profiles_via_xcode_api'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:271:in `all'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:320:in `find_by_bundle_id'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/sigh/lib/sigh/runner.rb:64:in `fetch_profiles'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/sigh/lib/sigh/runner.rb:20:in `run'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/sigh/lib/sigh/manager.rb:7:in `start'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:84:in `download_profile'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:58:in `block in all_create'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `each'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `all_create'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/export.rb:219:in `create_provisioning'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy/build.rb:44:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/command_builder.rb:69:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/lib/deploygate/command_builder.rb:127:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@YouShinStransa 
Thank you feedback!

Please try update openssl.

## If you use homebrew

```
brew update && brew upgrade openssl
```

## If you use rvm

```
rvm osx-ssl-certs update all
```

## reference

https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#im-getting-an-ssl-error

**Comment by henteko** [comment]
Thank you feedback.
Please try again on the new version (v0.6.8).
