### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by aquahika** [DeployGate/deploygate-cli#188]
# Status
deploygate-cli ver 0.6.0

# Error message
Error parsing xcode file using `xcodebuild -list -workspace /Users/hikaru/Documents/iOS/AppLabelPublisher/AppLabelPublisher.xcodeproj/project.xcworkspace`

# Backtrace
```
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/project.rb:398:in `raw_info'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/project.rb:464:in `parsed_info'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/project.rb:102:in `schemes'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/xcode/analyze.rb:27:in `initialize'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy/build.rb:37:in `new'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy/build.rb:37:in `ios'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/command_builder.rb:69:in `block (2 levels) in run'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/lib/deploygate/command_builder.rb:127:in `run'
/Users/hikaru/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deploygate-0.6.0/bin/dg:6:in `<top (required)>'
/Users/hikaru/.rbenv/versions/2.4.1/bin/dg:23:in `load'
/Users/hikaru/.rbenv/versions/2.4.1/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Please execute the command again on the current version.
Please re-open this issue if you get this error.
