### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by Yerkenabildin** [DeployGate/deploygate-cli#191]
# Status
deploygate-cli ver 0.6.0

# Error message
execution expired

# Backtrace
```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `syswrite'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `do_write'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/buffering.rb:343:in `write'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:500:in `block in dump'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:497:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:497:in `dump'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1280:in `do_get_stream'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1050:in `block (2 levels) in do_request_async'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/usr/local/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1049:in `block in do_request_async'
```

**Comment by henteko** [comment]
Please execute the command again.
Please re-open this issue if you get this error.
