### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by kimri** [DeployGate/deploygate-cli#204]
# Status
deploygate-cli ver 0.5.4

# Error message
execution expired

# Backtrace
```
/Users/kinnichi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `syswrite'
/Users/kinnichi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `do_write'
/Users/kinnichi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:342:in `write'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:92:in `<<'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:582:in `dump_file'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:500:in `block in dump'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:497:in `each'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:497:in `dump'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/http.rb:962:in `dump'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:510:in `block in query'
/Users/kinnichi/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:508:in `query'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:174:in `query'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1278:in `do_get_stream'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1048:in `block (2 levels) in do_request_async'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
/Users/kinnichi/workspace/hiroshimabank/hiroshimabank-android/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1047:in `block in do_request_async'
```

**Comment by henteko** [comment]
Please execute the command again.
Please re-open this issue if you get this error.
