### ISSUE TITLE
Commands::AddDevices Error: Errno::ENOENT

### ISSUE THREAD

**Issue by bohebohe** [DeployGate/deploygate-cli#205]
# Status
deploygate-cli ver 0.6.1

# Error message
No such file or directory

# Backtrace
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `collect!'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `find'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/lib/deploygate/xcode/ios.rb:56:in `ios_root?'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/lib/deploygate/project.rb:8:in `ios?'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/lib/deploygate/commands/add_devices.rb:10:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/lib/deploygate/command_builder.rb:128:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.6.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Please execute the command again on the current version.
Please re-open this issue if you get this error.
