### ISSUE TITLE
Commands::Deploy Error: NoMethodError

### ISSUE THREAD

**Issue by takaaki7** [DeployGate/deploygate-cli#209]
# Status
deploygate-cli ver 0.6.2

# Error message
undefined method `build_configuration_list' for nil:NilClass

# Backtrace
```
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/xcode/analyze.rb:141:in `target_build_configration'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/xcode/analyze.rb:87:in `target_xcode_setting_provisioning_profile_uuid'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:42:in `ios'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:128:in `run'
/Users/takaaki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/bin/dg:6:in `<top (required)>'
/Users/takaaki/.rbenv/versions/2.3.1/bin/dg:23:in `load'
/Users/takaaki/.rbenv/versions/2.3.1/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@takaaki7 Please read this issue comment.
https://github.com/DeployGate/deploygate-cli/issues/242#issuecomment-402154112

Also, this issue will close, because it duplicated.
