### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by atsushiootani** [DeployGate/deploygate-cli#211]
# Status
deploygate-cli ver 0.6.2

# Error message
Error parsing xcode file using `xcodebuild -list -workspace MY_APP.xcodeproj/project.xcworkspace`

# Backtrace
```
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:398:in `raw_info'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:464:in `parsed_info'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:102:in `schemes'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/xcode/analyze.rb:29:in `initialize'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:38:in `new'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:38:in `ios'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:128:in `run'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/bin/dg:6:in `<top (required)>'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/bin/dg:23:in `load'
/Users/otaniatsushi1/.rbenv/versions/2.3.1/bin/dg:23:in `<main>'
```

**Comment by atsushiootani** [comment]
resolved.
