### ISSUE TITLE
Commands::AddDevices Error: FastlaneCore::Interface::FastlaneBuildFailure

### ISSUE THREAD

**Issue by kumamotone** [DeployGate/deploygate-cli#212]
# Status
deploygate-cli ver 0.6.2

# Error message
Error packaging up the application

# Backtrace
```
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `build_failure!'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/gym/lib/gym/error_handler.rb:109:in `handle_package_error'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/gym/lib/gym/runner.rb:114:in `block in package_app'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/gym/lib/gym/runner.rb:110:in `package_app'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/gym/lib/gym/runner.rb:20:in `run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/gym/lib/gym/manager.rb:14:in `work'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/xcode/ios.rb:31:in `build'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:57:in `ios'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/add_devices.rb:71:in `build!'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/add_devices.rb:57:in `device_register'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/commands/add_devices.rb:29:in `run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.67.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/lib/deploygate/command_builder.rb:128:in `run'
/Users/kakumamo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/deploygate-0.6.2/bin/dg:6:in `<top (required)>'
/Users/kakumamo/.rbenv/versions/2.3.3/bin/dg:22:in `load'
/Users/kakumamo/.rbenv/versions/2.3.3/bin/dg:22:in `<main>'
```

**Comment by kumamotone** [comment]
Error message:

```
Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'xxxxxxxxxx' were found" UserInfo={NSLocalizedDescription=No profiles for 'xxxxxxxxxxx' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS Ad Hoc provisioning profiles matching 'xxxxxxxxxxx'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

** EXPORT FAILED ** 
[21:31:25]: Exit status: 70
```

This issue may be related.
https://github.com/fastlane/fastlane/issues/10251
