### ISSUE TITLE
Commands::Deploy Error: TypeError

### ISSUE THREAD

**Issue by Tsunehiko511** [DeployGate/deploygate-cli#216]
Unityでiosアプリをビルドし，そのファイルがある場所でdg deployを押したらエラーが出ました。

# Status
deploygate-cli ver 0.6.3

# Error message
no implicit conversion of nil into String

# Backtrace
```
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/xcode/analyze.rb:24:in `dirname'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/xcode/analyze.rb:24:in `initialize'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:38:in `new'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:38:in `ios'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/lib/deploygate/command_builder.rb:128:in `run'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.6.3/bin/dg:6:in `<top (required)>'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/bin/dg:23:in `load'
/Users/shimadzutsunehiko/.rbenv/versions/2.2.4/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
一度Xcodeを開き証明書の設定をすることで解決したようなのでCloseします
