### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by fuwamaki** [DeployGate/deploygate-cli#220]
# Status
deploygate-cli ver 0.6.3

# Error message
No Schemes found

# Backtrace
```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:143:in `select_scheme'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/xcode/analyze.rb:32:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:38:in `new'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:38:in `ios'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/lib/deploygate/command_builder.rb:128:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.3/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Please execute the command again on the current version.
Please re-open this issue if you get this error.
