### ISSUE TITLE
Commands::Deploy Error: HTTPClient::SendTimeoutError

### ISSUE THREAD

**Issue by nuKs** [DeployGate/deploygate-cli#221]
# Status
deploygate-cli ver 0.6.3

# Error message
execution expired

# Backtrace
```
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `syswrite'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `do_write'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:342:in `write'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:500:in `block in dump'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:497:in `each'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:497:in `dump'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1280:in `do_get_stream'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1050:in `block (2 levels) in do_request_async'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/Users/medullosuprarenal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1049:in `block in do_request_async'
```

**Comment by nuKs** [comment]
I've seen this issue is recurrent here, but no info on how to fix it. Any idea? 

I've just tried `sudo gem install fastlane` to upgrade fastlane (and it's not working).
I've seen similar issues on other project so I suppose it's not related to deploygate https://stackoverflow.com/questions/39080012/execution-expired-error-when-uploading-a-large-file-to-google-cloud-storage-usin

**Comment by nuKs** [comment]
quick fix: The IPA has already been built once I get this error. I can upload .ipa manually using the deploygate dashboard (on the deploygate website).

**Comment by henteko** [comment]
Please execute the command again.
Please re-open this issue if you get this error.
