### ISSUE TITLE
Commands::Deploy Error: DeployGate::Deploy::UploadError

### ISSUE THREAD

**Issue by TakafumiNanao** [DeployGate/deploygate-cli#23]
# Error message
application create error: limit

# Backtrace
```
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/deploy.rb:27:in `push'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/commands/deploy/push.rb:28:in `upload'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/commands/deploy.rb:19:in `run'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/command_builder.rb:36:in `block (2 levels) in run'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/lib/deploygate/command_builder.rb:58:in `run'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.3/bin/dg:6:in `<top (required)>'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/bin/dg:23:in `load'
/Users/takafumi.nanao/.rbenv/versions/2.2.3/bin/dg:23:in `<main>'
```

**Comment by TakafumiNanao** [comment]
kotlinのプロジェクトビルドしてみたら、Uploadに失敗しました。
https://github.com/chibatching/NearbySample/tree/master

**Comment by henteko** [comment]
@TakafumiNanao 
upload対象のアカウントが、リミットに引っかかってこれ以上新規のアプリをuploadできなくなっています
upload対象のアカウントを変更(--userオプションでgroupに対してuploadできます)するか、ログインアカウントを変更($ dg logout)するか、アプリを削除するかしてください

また、upload失敗時のエラーメッセージが分かりにくいので、別issueとして対応します

**Comment by punchdrunker** [comment]
thx!
