### ISSUE TITLE
Commands::AddDevices Error: Spaceship::TunesClient::ITunesConnectError

### ISSUE THREAD

**Issue by emosei** [DeployGate/deploygate-cli#234]
# Status
deploygate-cli ver 0.6.4

# Error message
{"authType"=>"hsa2"}
dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=LQUTSHOeU+DvLpdBFn2WFthXRJUZIEGZaBgIABLnrMUHI30=; Max-Age=31536000; Expires=Wed, 29-May-2019 18:41:40 GMT; Domain=apple.com; Path=/; Secure; HttpOnly

# Backtrace
```
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/client.rb:478:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/client.rb:646:in `do_login'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/client.rb:395:in `login'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/client.rb:116:in `login'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/spaceship.rb:92:in `login'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/sigh/lib/sigh/runner.rb:15:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/sigh/lib/sigh/manager.rb:7:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:84:in `download_profile'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:58:in `block in all_create'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `all_create'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:71:in `build!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:57:in `device_register'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:29:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.5/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.5/lib/commander/command.rb:182:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.5/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.5/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.5/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:128:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.6.4/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Please execute the command again on the current version.
Please re-open this issue if you get this error.
