### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by suzuhiroruri** [DeployGate/deploygate-cli#238]
# Status
deploygate-cli ver 0.6.4

# Error message
Error parsing xcode file using `xcodebuild -list -workspace /Users/hir-suzuki/repoisitory/blueBook_repo/blueBook.xcodeproj/project.xcworkspace`

# Backtrace
```
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:398:in `raw_info'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:464:in `parsed_info'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/project.rb:102:in `schemes'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/xcode/analyze.rb:29:in `initialize'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/commands/deploy/build.rb:38:in `new'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/commands/deploy/build.rb:38:in `ios'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.5/lib/commander/command.rb:182:in `call'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.5/lib/commander/command.rb:153:in `run'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.5/lib/commander/runner.rb:446:in `run_active_command'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.5/lib/commander/delegates.rb:15:in `run!'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:128:in `run'
/Users/hir-suzuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/deploygate-0.6.4/bin/dg:6:in `<top (required)>'
/Users/hir-suzuki/.rbenv/versions/2.5.0/bin/dg:23:in `load'
/Users/hir-suzuki/.rbenv/versions/2.5.0/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Please execute the command again on the current version.
Please re-open this issue if you get this error.
