### ISSUE TITLE
Commands::AddDevices Error: TypeError

### ISSUE THREAD

**Issue by ryota777** [DeployGate/deploygate-cli#245]
# Status
deploygate-cli ver 0.6.5

# Error message
no implicit conversion of nil into String

# Backtrace
```
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/xcode/analyze.rb:24:in `dirname'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/xcode/analyze.rb:24:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/commands/add_devices.rb:103:in `new'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/commands/add_devices.rb:103:in `bundle_id'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/commands/add_devices.rb:24:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/lib/deploygate/command_builder.rb:128:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.5/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
The problem was that the project.xcworkspace in the .xcodeproj directory was not generated.
When you open a project in Xcode, project.xcworkspace is generated.
Then try dg add-devices again.
