### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by Tsunehiko511** [DeployGate/deploygate-cli#256]
# Status
deploygate-cli ver 0.6.4

# Error message
Can't find class 'adhoc'

# Backtrace
```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:202:in `factory'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `block in all'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `map!'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `all'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:364:in `find_by_bundle_id'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/sigh/lib/sigh/runner.rb:64:in `fetch_profiles'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/sigh/lib/sigh/runner.rb:20:in `run'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/sigh/lib/sigh/manager.rb:7:in `start'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:84:in `download_profile'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:58:in `block in all_create'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `each'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `all_create'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:71:in `build!'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:57:in `device_register'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/commands/add_devices.rb:29:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/lib/deploygate/command_builder.rb:128:in `run'
/Library/Ruby/Gems/2.3.0/gems/deploygate-0.6.4/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Same problem: #266
