### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by Tsunehiko511** [DeployGate/deploygate-cli#266]
# Status
deploygate-cli ver 0.6.7

# Error message
Can't find class 'adhoc'

# Backtrace
```
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:202:in `factory'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `block in all'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `map!'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:316:in `all'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:364:in `find_by_bundle_id'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/sigh/lib/sigh/runner.rb:64:in `fetch_profiles'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/sigh/lib/sigh/runner.rb:20:in `run'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/sigh/lib/sigh/manager.rb:7:in `start'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/xcode/member_centers/provisioning_profile.rb:84:in `download_profile'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/xcode/member_centers/provisioning_profile.rb:58:in `block in all_create'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `each'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/xcode/member_centers/provisioning_profile.rb:56:in `all_create'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/commands/add_devices.rb:71:in `build!'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/commands/add_devices.rb:57:in `device_register'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/commands/add_devices.rb:29:in `run'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/command_builder.rb:91:in `block (2 levels) in run'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/lib/deploygate/command_builder.rb:128:in `run'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/deploygate-0.6.7/bin/dg:6:in `<top (required)>'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/bin/dg:23:in `load'
/Users/shimazutsunehiko/.rbenv/versions/2.5.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@Tsunehiko511 
Thank you feedback!
Please try again on the new version.
https://rubygems.org/gems/deploygate/versions/0.7.0
