### ISSUE TITLE
Commands::Deploy Error: RuntimeError

### ISSUE THREAD

**Issue by jeffeom** [DeployGate/deploygate-cli#268]
# Status
deploygate-cli ver 0.6.6

# Error message
[!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

# Backtrace
```
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:203:in `initialize_from_file'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:103:in `open'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/xcode/analyze.rb:161:in `target_project'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/xcode/analyze.rb:157:in `target_project_setting'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/xcode/analyze.rb:129:in `target_provisioning_info'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/xcode/analyze.rb:95:in `provisioning_style'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/commands/deploy/build.rb:43:in `ios'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/command_builder.rb:70:in `block (2 levels) in run'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.57.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/lib/deploygate/command_builder.rb:128:in `run'
/Users/jeffeom/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/deploygate-0.6.6/bin/dg:6:in `<top (required)>'
/Users/jeffeom/.rbenv/versions/2.4.3/bin/dg:23:in `load'
/Users/jeffeom/.rbenv/versions/2.4.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@jeffeom 
Thank you feedback!
Please update the dg command to v0.7.0
