### ISSUE TITLE
Commands::Deploy Error: DeployGate::Deploy::UploadError

### ISSUE THREAD

**Issue by yoneapp** [DeployGate/deploygate-cli#32]
# Status
deploygate-cli ver 0.0.4

# Error message
application create error: limit

# Backtrace
```
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/deploy.rb:27:in `push'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/commands/deploy/push.rb:28:in `upload'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/commands/deploy/build.rb:66:in `ios'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/command_builder.rb:37:in `block (2 levels) in run'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/lib/deploygate/command_builder.rb:59:in `run'
/Users/yoneapp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.0.4/bin/dg:6:in `<top (required)>'
/Users/yoneapp/.rbenv/versions/2.2.3/bin/dg:23:in `load'
/Users/yoneapp/.rbenv/versions/2.2.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@yoneapp 
Thanks for the feedback.

This error is the upload limit on the number of apps .
Please check the DeployGate account .

In addition , this issue also please refer to.
https://github.com/DeployGate/deploygate-cli/issues/23
