### ISSUE TITLE
Commands::Deploy Error: DeployGate::Deploy::UploadError

### ISSUE THREAD

**Issue by arusu0629** [DeployGate/deploygate-cli#66]
# Status
deploygate-cli ver 0.1.1

# Error message
application create error: Type mismatch. Total bytes read: 77 Bytes available: 344505 Offset: 77

# Backtrace
```
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/deploy.rb:28:in `push'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/commands/deploy/push.rb:29:in `upload'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/commands/deploy.rb:19:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:43:in `block (2 levels) in run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:426:in `run_active_command'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:98:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/bin/dg:6:in `<top (required)>'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `load'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@arusu0629 
Thanks for the feedback :)

What you tell me whether tried to upload the app?

**Comment by henteko** [comment]
This issue will get closed because old.
