### ISSUE TITLE
Commands::Deploy Error: RuntimeError

### ISSUE THREAD

**Issue by aritaku** [DeployGate/deploygate-cli#67]
# Status
deploygate-cli ver 0.1.1

# Error message
[31mError packaging up the application[0m

# Backtrace
```
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/gym-1.0.0/lib/gym/error_handler.rb:86:in `handle_package_error'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/gym-1.0.0/lib/gym/runner.rb:102:in `block in package_app'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.31.0/lib/fastlane_core/command_executor.rb:61:in `call'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.31.0/lib/fastlane_core/command_executor.rb:61:in `execute'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/gym-1.0.0/lib/gym/runner.rb:98:in `package_app'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/gym-1.0.0/lib/gym/runner.rb:16:in `run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/gym-1.0.0/lib/gym/manager.rb:8:in `work'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/xcode/ios.rb:29:in `build'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/commands/deploy/build.rb:40:in `ios'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:43:in `block (2 levels) in run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:98:in `run'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/gems/deploygate-0.1.1/bin/dg:6:in `<top (required)>'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/bin/dg:23:in `load'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/bin/dg:23:in `<main>'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/arimuratakuma/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by henteko** [comment]
It will close because this issue is a known
#17
