### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by arusu0629** [DeployGate/deploygate-cli#68]
# Status
deploygate-cli ver 0.1.1

# Error message
Not local install certificate

# Backtrace
```
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:48:in `all_create'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/xcode/member_centers/provisioning_profile.rb:21:in `create!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/commands/add_devices.rb:47:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:61:in `block (2 levels) in run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/lib/deploygate/command_builder.rb:98:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.1/bin/dg:6:in `<top (required)>'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `load'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
This issue it will close because there is the same thing.
#74
