### ISSUE TITLE
Commands::Deploy Error: RuntimeError

### ISSUE THREAD

**Issue by shoya140** [DeployGate/deploygate-cli#73]
# Status
deploygate-cli ver 0.1.2

# Error message
[31mError packaging up the application[0m

# Backtrace
```
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/error_handler.rb:86:in `handle_package_error'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:102:in `block in package_app'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `call'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `execute'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:98:in `package_app'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/runner.rb:16:in `run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.0.0/lib/gym/manager.rb:8:in `work'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/xcode/ios.rb:29:in `build'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:40:in `ios'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:106:in `run'
/Users/shoya/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/deploygate-0.1.2/bin/dg:6:in `<top (required)>'
/Users/shoya/.rbenv/versions/2.2.4/bin/dg:23:in `load'
/Users/shoya/.rbenv/versions/2.2.4/bin/dg:23:in `<main>'
```

And the final output is as below. Thank you for your supporting.

```
** EXPORT FAILED **
[19:31:56]: Exit status: 70
Current Xcode used to build: /Applications/Xcode.app/Contents/Developer
 (via xcode-select)
Error: Error packaging up the application
```

**Comment by henteko** [comment]
It will close because this issue is a known
#17
