### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by arusu0629** [DeployGate/deploygate-cli#74]
# Status
deploygate-cli ver 0.1.2

# Error message
Not local install certificate

# Backtrace
```
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/member_centers/provisioning_profile.rb:48:in `all_create'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/member_centers/provisioning_profile.rb:21:in `create!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/add_devices.rb:47:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:69:in `block (2 levels) in run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:106:in `run'
/Users/e125726/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/bin/dg:6:in `<top (required)>'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `load'
/Users/e125726/.rbenv/versions/2.1.2/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@arusu0629 
Thanks for the feedback :)

This error is output if the certificate is not installed on the local.
Please try to confirm the certificate in the [Apple Developer](https://developer.apple.com/membercenter/index.action).

**Comment by henteko** [comment]
This issue will get closed because old.
