### ISSUE TITLE
Commands::Deploy Error: NoMethodError

### ISSUE THREAD

**Issue by urouro** [DeployGate/deploygate-cli#80]
# Status
deploygate-cli ver 0.1.2

# Error message
undefined method `each' for nil:NilClass

# Backtrace
```
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:136:in `select_profile'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:239:in `block (3 levels) in select_teams'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline/menu.rb:312:in `call'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline/menu.rb:312:in `select'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline.rb:366:in `choose'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:235:in `select_teams'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:25:in `provisioning_profile'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:106:in `run'
/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/bin/dg:6:in `<top (required)>'
/Users/kn/.rbenv/versions/2.1.4/bin/dg:23:in `load'
/Users/kn/.rbenv/versions/2.1.4/bin/dg:23:in `<main>'
```

Here are the full output.

```
% dg deploy --trace
[10:48:01]: xcrun xcodebuild -list -workspace '/Users/kn/Dev/ios/Ideacards/IdeaCards.xcodeproj/project.xcworkspace'
1. Kenta Nakai U34SUZJMKE
2. My client company's team C3XXXXXXXX
Please select a team
1
Error: undefined method `each' for nil:NilClass

Do you want to report this issue on GitHub? (y/n) |n| y
Please open GitHub issue: https://github.com/...

/Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:136:in `select_profile': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:239:in `block (3 levels) in select_teams'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline/menu.rb:312:in `call'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline/menu.rb:312:in `select'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/highline-1.7.8/lib/highline.rb:366:in `choose'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:235:in `select_teams'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/xcode/export.rb:25:in `provisioning_profile'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:36:in `ios'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy/build.rb:17:in `run'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/commands/deploy.rb:16:in `run'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/lib/deploygate/command_builder.rb:106:in `run'
	from /Users/kn/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/deploygate-0.1.2/bin/dg:6:in `<top (required)>'
	from /Users/kn/.rbenv/versions/2.1.4/bin/dg:23:in `load'
	from /Users/kn/.rbenv/versions/2.1.4/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
@urouro 
Thanks for the feedback :)

This error was fixed in [v0.2.0](https://rubygems.org/gems/deploygate/versions/0.2.0)!
Thank you ;)
