### ISSUE TITLE
Commands::Deploy Error: NoMethodError

### ISSUE THREAD

**Issue by hoanganh6491** [DeployGate/deploygate-cli#87]
Hi support team,

I have this issue but do not know how to fix it :(

Please help me out :(
thank you so much!
# Status

deploygate-cli ver 0.2.0
# Error message

undefined method `build_configuration_list' for nil:NilClass
# Backtrace

```
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/analyze.rb:52:in `target_build_configration'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/analyze.rb:45:in `target_xcode_setting_provisioning_profile_uuid'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy/build.rb:34:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.7/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:106:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thanks for your report!

**Comment by henteko** [comment]
This issue will get closed because old.
