### ISSUE TITLE
Commands::Deploy Error: SocketError

### ISSUE THREAD

**Issue by m0a** [DeployGate/deploygate-cli#88]
# Status
deploygate-cli ver 0.2.0

# Error message
getaddrinfo: nodename nor servname provided, or not known (https://deploygate.com:443)

# Backtrace
```
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:800:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:800:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:800:in `create_socket'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:749:in `block in connect'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/timeout.rb:120:in `timeout'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:748:in `connect'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:606:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient/session.rb:161:in `query'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:1070:in `do_get_block'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:873:in `block in do_request'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:966:in `protect_keep_alive_disconnected'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:872:in `do_request'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:760:in `request'
/usr/local/lib/ruby/gems/2.3.0/gems/httpclient-2.2.7/lib/httpclient.rb:663:in `get'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/api/v1/base.rb:20:in `get'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/api/v1/session.rb:12:in `show'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/api/v1/session.rb:22:in `check'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/session.rb:17:in `login?'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy.rb:9:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:106:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
このissueは [v0.2.1](https://rubygems.org/gems/deploygate/versions/0.2.1)で解決したと思うのでcloseします！
