### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by toruuetani** [DeployGate/deploygate-cli#90]
# Status
deploygate-cli ver 0.2.0

# Error message
Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed

# Backtrace
```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/portal_client.rb:318:in `download_certificate'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/certificate.rb:298:in `download_raw'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:49:in `block in all_create'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `each'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:47:in `all_create'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:26:in `create!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/commands/add_devices.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:69:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:106:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thanks for your report!

**Comment by henteko** [comment]
@toruuetani 
ありがとうございます！
新しいversionを作ってみたので、こちらで試していただけませんか？
https://deploygate.s3.amazonaws.com/clients/deploygate-0.2.1.pre.gem

gemファイルをダウンロードして、以下のようにコマンドを叩くとインストールできます

```
$ gem install deploygate-0.2.1.pre.gem
```

インストール後、versionが0.2.1.preになっていることをご確認ください

```
$ dg version
```

**Comment by henteko** [comment]
このissueは [v0.2.1](https://rubygems.org/gems/deploygate/versions/0.2.1)で解決したと思いますのでcloseします！

**Comment by toruuetani** [comment]
v0.2.1で試したところ、問題なくアップロードまでできました。
対応ありがとうございました。
