### ISSUE TITLE
Commands::AddDevices Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by masuhara** [DeployGate/deploygate-cli#93]
# Status

deploygate-cli ver 0.2.1
# Error message

{"creationTimestamp"=>"2016-03-18T05:23:11Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/QH65B2/listTeams.action", "responseId"=>"8b671775-a6a1-412f-b0d4-30689a9be369"}
# Backtrace

```
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:300:in `parse_response'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:63:in `teams'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:79:in `select_team'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_center.rb:12:in `initialize'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/2.2.0/singleton.rb:141:in `new'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/2.2.0/singleton.rb:141:in `block in instance'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/2.2.0/singleton.rb:139:in `synchronize'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/2.2.0/singleton.rb:139:in `instance'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_centers/device.rb:27:in `register!'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/lib/deploygate/commands/add_devices.rb:40:in `run'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:86:in `block (2 levels) in run'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Users/Masuhara/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/Users/Masuhara/.rbenv/versions/2.2.3/bin/dg:23:in `load'
/Users/Masuhara/.rbenv/versions/2.2.3/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
