### ISSUE TITLE
Commands::Deploy Error: FastlaneCore::Interface::FastlaneError

### ISSUE THREAD

**Issue by horit07** [DeployGate/deploygate-cli#94]
# Status

deploygate-cli ver 0.2.1
# Error message

Error building the application - see the log above
# Backtrace

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/error_handler.rb:52:in `handle_build_error'
/Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/runner.rb:95:in `block in build_app'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/command_executor.rb:85:in `call'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/command_executor.rb:85:in `execute'
/Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/runner.rb:91:in `build_app'
/Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/runner.rb:12:in `run'
/Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/manager.rb:10:in `work'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/ios.rb:29:in `build'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:40:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/usr/bin/dg:22:in `load'
/usr/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
This issue will get closed because old.
