### ISSUE TITLE
Commands::Deploy Error: RuntimeError

### ISSUE THREAD

**Issue by usatie** [DeployGate/deploygate-cli#96]
# Status

deploygate-cli ver 0.2.1
# Error message

Could not find latest API Key from the Dev Portal - the server might be slow right now
# Backtrace

```
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:30:in `api_key'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:38:in `send_login_request'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:219:in `do_login'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:182:in `login'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:60:in `login'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:22:in `login'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:77:in `login'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_center.rb:11:in `initialize'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:142:in `new'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `instance'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_centers/app.rb:10:in `initialize'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:202:in `new'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:202:in `create_provisioning'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Users/SHUN/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/Users/SHUN/.rbenv/versions/2.3.0/bin/dg:23:in `load'
/Users/SHUN/.rbenv/versions/2.3.0/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you, feedback!
Please try since has released a new ver!
https://rubygems.org/gems/deploygate/versions/0.2.2

**Comment by henteko** [comment]
This issue will get closed because old.
