### ISSUE TITLE
Commands::Deploy Error: RuntimeError

### ISSUE THREAD

**Issue by ktaka** [DeployGate/deploygate-cli#99]
# Status
deploygate-cli ver 0.2.1

# Error message
Could not find latest API Key from the Dev Portal - the server might be slow right now

# Backtrace
```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:30:in `api_key'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:38:in `send_login_request'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:219:in `do_login'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:182:in `login'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:60:in `login'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:22:in `login'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/spaceship.rb:77:in `login'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_center.rb:11:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:141:in `block in instance'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/singleton.rb:139:in `instance'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/member_centers/app.rb:10:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:202:in `new'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:202:in `create_provisioning'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy/build.rb:17:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:68:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/lib/deploygate/command_builder.rb:123:in `run'
/Library/Ruby/Gems/2.0.0/gems/deploygate-0.2.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you, feedback!
This issue is closed because it is the same as # 96 .
